name: build games
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - games/**
jobs:
  push:
    name: "games:arma3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - arma3
          
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v2.0.0"
          buildkitd-flags: --debug
      - uses: docker/build-push-action@v3
        with:
          registry: ghcr.io
          context: ./games/arma3/
          file: ./games/arma3/Dockerfile
          platforms: linux/amd64/arm64
          push: true
          tags: |
            ghcr.io/gangstervogel/games:arma3